name: Release trigger workflow

on:
  release:
    types: [published]

jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug release payload
        run: |
          echo "${{ toJson(github.event) }}"

      - name: 顯示當前的 target_commitish
        id: get_tag_commit
        run: |
          echo "target_commitish=${{ github.event.release.target_commitish}}"
          echo "tag=${{ github.event.release.tag_name}}"
          git fetch --all --tags
          TAG_COMMIT=$(git rev-list -n 1 refs/tags/${{ github.event.release.tag_name }})
          echo "TAG_COMMIT=$TAG_COMMIT" >> $GITHUB_OUTPUT

      - name: 顯示本次 release 的 tag 是否屬於 main 分支
        env:
          TAG_COMMIT: ${{ steps.get_tag_commit.outputs.TAG_COMMIT }}
        run: |
          if git merge-base --is-ancestor "$TAG_COMMIT" origin/main; then
            echo "$TAG_COMMIT is an ancestor of origin/main"
          else
            echo "$TAG_COMMIT is NOT an ancestor of origin/main"
          fi

      - name: 測試分支才用，根本
        env:
          TAG_COMMIT: ${{ steps.get_tag_commit.outputs.TAG_COMMIT }}
        run: |
          git merge-base --is-ancestor "$TAG_COMMIT" origin/main
