name: Release trigger workflow

on:
  release:
    types: [published]

jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
        fetch-depth: 0

      - name: 顯示當前的 target_commitish
        run: |
          echo "target_commitish=${{ github.event.target_commitish}}"
          echo "tag=${{ github.event.release.tag_name}}"
          git fetch --all --tags
          TAG_COMMIT=$(git rev-list -n 1 refs/tags/${{ github.event.release.tag_name }})
          echo "tag commit=$TAG_COMMIT"

      - name: 顯示本次 release 的 tag 是否屬於 main 分支
        run: |
          git merge-base --is-ancestor "$TAG_COMMIT" origin/main
